### ISSUE TITLE
Runtime dependency on dbus-daemon

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [ldo/dbussy_examples#1]
Hey,
am just going through your code examples, and wanted to try out one where a service is being registered on the bus.

However the examples fails the following way:

```
./bigben_server
Traceback (most recent call last):
  File "./bigben_server", line 139, in <module>
    conn = dbus.Connection.bus_get(DBUS.BUS_SESSION, private = False)
  File "/usr/lib/python3.5/site-packages/dbussy.py", line 2843, in bus_get
    my_error.raise_if_set()
  File "/usr/lib/python3.5/site-packages/dbussy.py", line 4869, in raise_if_set
    raise DBusError(self.name, self.message)
dbussy.DBusError: org.freedesktop.DBus.Error.NotSupported -- Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

This is most likely an issue on my side given that it's the same issue that pops
up if I try to run, for example `dbus-monitor`.

However `./introspect system org.bluez /org/bluez/hci0` seems to be running
ok.

How do runtime dependencies for those two examples differ?

**Comment by ldo** [comment]
Are you logged into a GUI session? Otherwise you won’t have a session bus.

As I understand it, the environment variable `DBUS_SESSION_BUS_ADDRESS` needs to point to the address for connecting to the session bus. For example, in my current session, this is defined as

    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

Otherwise, this is possibly a question for the [dbus mailing list](https://lists.freedesktop.org/mailman/listinfo/dbus).

**Comment by TheMeaningfulEngineer** [comment]
> Are you logged into a GUI session? Otherwise you won’t have a session bus.

Nope, it's a CLI only system.

I've modified it to use the system bus which seems to solve the above issue.
Changed [this line](https://github.com/ldo/dbussy_examples/blob/master/bigben_server#L139
) to:

```
conn = dbus.Connection.bus_get(DBUS.BUS_SYSTEM, private = False)
```

Got some permission errors but it does seem to drop the session bus dependency.

**Comment by TheMeaningfulEngineer** [comment]
This was a misunderstanding of d-bus from my side. 
The example has been written for systems that have a session bus 
that wasn't the case for me on a headless embedded system.

Found a good explanation why here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690530

Closing issue :)

**Comment by jarrott616** [comment]
> Hey,
> am just going through your code examples, and wanted to try out one where a service is being registered on the bus.
> 
> However the examples fails the following way:
> 
> ```
> ./bigben_server
> Traceback (most recent call last):
>   File "./bigben_server", line 139, in <module>
>     conn = dbus.Connection.bus_get(DBUS.BUS_SESSION, private = False)
>   File "/usr/lib/python3.5/site-packages/dbussy.py", line 2843, in bus_get
>     my_error.raise_if_set()
>   File "/usr/lib/python3.5/site-packages/dbussy.py", line 4869, in raise_if_set
>     raise DBusError(self.name, self.message)
> dbussy.DBusError: org.freedesktop.DBus.Error.NotSupported -- Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
> ```
> 
> This is most likely an issue on my side given that it's the same issue that pops
> up if I try to run, for example `dbus-monitor`.
> 
> However `./introspect system org.bluez /org/bluez/hci0` seems to be running
> ok.
> 
> How do runtime dependencies for those two examples differ?

Write ., Only!
